env:
  BAZEL_REMOTE_CACHE_URL: grpcs://proxy.stg.flare.build
  BAZEL_BES_BACKEND: grpcs://bes.stg.flare.build
  BAZEL_BES_RESULTS_URL: "https://insights.stg.flare.build/invocations/"
  FLARE_INSIGHTS_API_URL: "https://api.stg.flare.build"

steps:
  - label: ":macos: :bazel: integation tests"
    key: bazel-build
    agents:
      queue: macos
    command: .buildkite/integration-tests.sh
    timeout_in_minutes: 28
